project:
  type: website

website:
  #title: "The Right Place"
  #image: opengraph.png
  #page-navigation: true
  
  
  navbar:
    foreground: "#5d5a88"
    logo: "logo.png"
    logo-href: "The Right Place" 
      
    #left: 
      
      
    right:
      - text: About Us
        href: index.qmd
        
      - text: Project Proposal
        href: project_proposal.qmd
        
      - icon: github
        href: https://github.com/G1T777/IS415-Project
        aria-label: GitHub
        
format:
  html:
    theme: litera
    css: styles.css
    toc: true
    mainfont: monospace
    
    fontcolor: "#5d5a88"
    

editor: visual

